answers = {
    "method 1": {
        "step 1": "Place a pan on the stove, heating it on medium heat. Use a pan with enough space to allow for some running between eggs. An 8-inch pan is perfect for one egg, while you'll need a 12\" or bigger for 2-3 eggs at once.",
        "step 2": "Add some oil or butter to the pan as it gets warm. 1/2 a tablespoon or so should be enough per egg. As it heats up, swirl it to coat the entire bottom of the pan in your oil. Monitor the burner temperature to avoid browning the oil or butter. Using too big of a pan can result in sticking, since your oil is spread too thinly to cook just one egg on its own. Add a little more oil if this is the case. For incredibly rich eggs, use a small pat of bacon grease. Cooking sprays are a quick and easy ways to ensure your entire pan is coated.",
        "step 3": "Allow the pan to warm up until the butter/oil is hot, but not browning. A lower temperature is better; too high and you'll burn the oil and eggs quickly. You want the oil to just start shimmering or the butter to just start bubbling. When you add the egg the whites should sizzle just a little bit.",
        "step 4": "Break the first egg into a small dish or bowl and pour it in, or crack the egg right in the pan. You want to be gentle cracking so you don't break the yolk. Cracking the egg into a bowl first can help you get out any shells before cooking. As you drop the egg in, you should hear a slight sizzle, but there shouldn't be popping or violent splattering.",
        "step 5": "Cook the eggs, undisturbed, until the clear edges turn white. Once you can't see the bottom of the pan, since the whites have cooked closest to the surface, you're ready to go on to the next step. Do not try and move the eggs now, as they are gelatinous and will likely fall right back into place. This usually takes 1-3 minutes.",
        "step 6": "Cover the pan and lower the heat once the edges have turned white. Put a lid on the pan. This will trap some steam in the pan, cooking the tops of the eggs and helping the whites set. This is the best way to keep the yolk runny, as too much direct heat can cook the yolk from underneath before the white has totally cooked.",
        "step 7": "Observe the hardness of the yolk by lifting the pan lid and gently poking it with your finger. When there are no more jelly-like, clear bits of uncooked egg on the whites, your egg is ready. You can keep cooking for harder eggs, or flip it off and serve immediately. For your average, runny egg this process takes roughly 5 minutes from the second the egg hits the pan until it's done.",
        "step 8": "Lift the egg out of the pan with a quick, firm slide of the spatula. You want to move quickly lifting and removing the egg to avoid breaking it. Serve it and enjoy. Top with salt and pepper to taste while the egg is still hot."
        },
    "method 2": {
        "step 1": "Fry your egg in hot oil for a decadent, golden brown crust and runny yolk. To do so, heat up 4 tablespoons (60 ml) of olive oil instead of 1 or 1/2. When you crack the egg in, turn the pan so that the hot oil and egg slid to the edge of the pan, which is still over the heat. As it cooks, use a spoon to bathe the top of the egg in hot olive oil. Once the outsides are brown and crispy, remove the egg, garnish with salt and pepper, and serve. Be careful -- the oil will splatter and sizzle. This can cook an egg in just 30-60 seconds.",
        "step 2": "Flip eggs halfway through to make them over-easy. Instead of putting a lid on the pan, simply flip the egg over after the whites have set to cook the tops of the yolks quickly and crisply. Be sure you use plenty of oil, and maneuver the spatula with a quick, even motions to flip it without ripping it.",
        "step 3": "Serve an egg with toast for a simple breakfast. The classic fried egg is with toast, often paired with fruit or meat as well, is a staple of breakfasts the world over. For a simple, filling breakfast you can add: Spinach or arugula. Tomatoes and/or avocados Bacon, sausage, or ham. Cheese. Fried rice.",
        "step 4": "Serve a fried egg over leftovers to make a filling meal. Stir fried vegetables, lentils, rice, and even pasta get a boost of rich, warm flavor with a fried egg and some dripping yolk. If you need to quickly spice up/augment a leftover dish, look no further than the humble fried egg.",
        "step 5": "Place a fried egg on sandwiches or burgers for a rich, protein filled option. They make great sandwich on their own as well, stuffed into baguettes or on a bun with some cheese, avocado, and tomato. On top of a burger, an egg and the runny yolk can elevate the meat to new heights.",
        "step 6": "Make Huevos Rancheros. This easy breakfast dish is a bit like an open burrito. To make it, top 2-3 corn tortillas with black beans, avocado, tomato, cheese, and salsa, plus any other taco ingredients you enjoy. Top each tortilla creation with a fried egg and enjoy. Fried eggs also go well on potato or sweet potato hashes, so try potatoes for base instead of tortillas."
        }
    }
